# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyzer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalyzer.proto\x12\x08services\"\x16\n\x06\x44omain\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x89\x01\n\x11\x46ullDomainScoring\x12\x12\n\nfinalScore\x18\x01 \x01(\x02\x12\x15\n\rsemanticScore\x18\x02 \x01(\x02\x12\x15\n\rresourceScore\x18\x03 \x01(\x02\x12\x10\n\x08\x64gaScore\x18\x04 \x01(\x02\x12 \n\x03tag\x18\x05 \x01(\x0e\x32\x13.services.ScoreFlag*w\n\tScoreFlag\x12\x17\n\x13\x44OMAIN_SCORE_BENIGN\x10\x00\x12\x18\n\x14\x44OMAIN_SCORE_DUBIOUS\x10\x01\x12\x1b\n\x17\x44OMAIN_SCORE_SUSPICIOUS\x10\x02\x12\x1a\n\x16\x44OMAIN_SCORE_MALICIOUS\x10\x03\x32X\n\x15\x44omainAnalysisService\x12?\n\x0eGetFullScoring\x12\x10.services.Domain\x1a\x1b.services.FullDomainScoringb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyzer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCOREFLAG']._serialized_start=192
  _globals['_SCOREFLAG']._serialized_end=311
  _globals['_DOMAIN']._serialized_start=28
  _globals['_DOMAIN']._serialized_end=50
  _globals['_FULLDOMAINSCORING']._serialized_start=53
  _globals['_FULLDOMAINSCORING']._serialized_end=190
  _globals['_DOMAINANALYSISSERVICE']._serialized_start=313
  _globals['_DOMAINANALYSISSERVICE']._serialized_end=401
# @@protoc_insertion_point(module_scope)
