# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import analyzer_pb2 as analyzer__pb2


class DomainAnalysisServiceStub(object):
    """python -m grpc_tools.protoc -I. --python_out=../services --pyi_out=../services --grpc_python_out=../services analyzer.proto

    import "google/protobuf/timestamp.proto";

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFullScoring = channel.unary_unary(
                '/services.DomainAnalysisService/GetFullScoring',
                request_serializer=analyzer__pb2.Domain.SerializeToString,
                response_deserializer=analyzer__pb2.FullDomainScoring.FromString,
                )


class DomainAnalysisServiceServicer(object):
    """python -m grpc_tools.protoc -I. --python_out=../services --pyi_out=../services --grpc_python_out=../services analyzer.proto

    import "google/protobuf/timestamp.proto";

    """

    def GetFullScoring(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DomainAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFullScoring': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFullScoring,
                    request_deserializer=analyzer__pb2.Domain.FromString,
                    response_serializer=analyzer__pb2.FullDomainScoring.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.DomainAnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DomainAnalysisService(object):
    """python -m grpc_tools.protoc -I. --python_out=../services --pyi_out=../services --grpc_python_out=../services analyzer.proto

    import "google/protobuf/timestamp.proto";

    """

    @staticmethod
    def GetFullScoring(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/services.DomainAnalysisService/GetFullScoring',
            analyzer__pb2.Domain.SerializeToString,
            analyzer__pb2.FullDomainScoring.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
